name: Auto Update AXSports

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Force Download AXSports files
        run: |
          # ফাইল ডাউনলোড
          curl -f -sL "https://raw.githubusercontent.com/srhady/axsports/main/playlist.m3u" -o playlist.m3u
          curl -f -sL "https://raw.githubusercontent.com/srhady/axsports/main/live_sports.json" -o live_sports.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u live_sports.json
          git commit -m "Auto update AXSports" || echo "No changes"
          git push
